# .github/workflows/deploy.yml

name: EC2로 자동배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 가져오기
        uses: actions/checkout@v4

      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: .env 파일 생성
        run: echo "${{ secrets.ENV }}" > .env

      - name: 빌드
        run: npm run build

      - name: 압축
        # NODE_MODULES 폴더는 압축하지 않는다.
        run: tar -czvf nextjs-aws-simulating.tar.gz .next .env package.json package-lock.json

      - name: 빌드
        run: npm run build

      - name: SSH로 EC2 접속하기
        uses: appleboy/ssh-action@v1
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: nextjs-aws-simulating.tar.gz
          target: /home/ubuntu/nextjs-aws-simulating/build

          envs: ENV
          script: |
            set -e
            rm -rf /home/ubuntu/nextjs-aws-simulating/current
            mkdir /home/ubuntu/nextjs-aws-simulating/current
            mv /home/ubuntu/nextjs-aws-simulating/build/nextjs-aws-simulating.tar.gz /home/ubuntu/nextjs-aws-simulating/current/nextjs-aws-simulating.tar.gz
            cd /home/ubuntu/nextjs-aws-simulating/current
            tar -xvf nextjs-aws-simulating.tar.gz
            npm ci
            pm2 kill
            pm2 start npm --name "nextjs-app" -- start
